# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Use the local JDK 21 so the daemon runs on Java 21
org.gradle.java.home=D\:\\java\\zulu21
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
# Mod Properties
mod_version=1.0
maven_group=mc506lw
archives_base_name=MSCPO-serverlist
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.6+1.21.11
